name: Wakatime Charts

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: [self-hosted, personal-pool, homelab]
    if: github.repository == 'thelabcorner/thelabcorner'
    steps:
      - uses: dvjn/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH_NAME: output
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
